version: '2'
services:
  namenode:
    image: sfedyakov/hadoop-271-cluster 
    container_name: namenode
    hostname: namenode
    networks:
      - appnet
    domainname: appnet
    ports:
      - "8088:8088"
      - "50090:50090"
      - "19888:19888"
    command: "/etc/bootstrap.sh -d -namenode"

  datanode:
    depends_on:
      - namenode
    image: sfedyakov/hadoop-271-cluster
    networks:
      - appnet
    command: "/etc/bootstrap.sh -d -datanode"

networks:
  appnet:
    external:
      name: appnet

